### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by ipapap** [hmf21/AerialVL#1]
Hi @hmf21, 
Thank you for your work!
Could you provide any updates on when the dataset might be released?

**Comment by ipapap** [comment]
Hi again @hmf21,
In VPR it seems that there is no map_database folder, only query_images. Am i missing something? 
Thank you!

**Comment by hmf21** [comment]
Hi @ipapap 
I have checked the uploaded dataset again, and confirmed that the database folder is contained.
Could you check the downloaded files again? And please cantact me if there is still any problem.
