### ISSUE TITLE
Extra dataset download link

### ISSUE THREAD

**Issue by Frost24K** [hmf21/AerialVL#3]
Hi,

Thank you for providing this excellent work! I would like to use this dataset for my research, but I encountered an issue with downloading it from Tsinghua Cloud—it cannot be downloaded all at once, worse still, the download process always stops for no reason.

Could you please provide a link for Baidu Netdisk or Google Drive? That would be very helpful to me!

**Comment by hmf21** [comment]
Hi @Frost24K,
Thanks for your suggestions. The updated downloading link will be added soon.

**Comment by Frost24K** [comment]
Thank you for your quick response. Looking forward to your update.

**Comment by hmf21** [comment]
Hi @Frost24K, the extra Baidu Netdisk link has been added. Please check the update in README.
